GET http://127.0.0.1:8002/api/empleados
Authorization: Bearer TU_TOKEN

GET http://127.0.0.1:8002/api/empleados/1
Authorization: Bearer TU_TOKEN

POST http://127.0.0.1:8002/api/empleados
Content-Type: application/json
Authorization: Bearer TU_TOKEN

{
    "nombres": "Pedro",
    "apellidos": "Gomez",
    "documento": "1000999888",
    "correo": "pedro@empresa.com",
    "telefono": "3009998888",
    "cargo": "Contador",
    "area": "Finanzas",
    "fecha_ingreso": "2025-03-01"
}

PUT http://127.0.0.1:8002/api/empleados/1
Content-Type: application/json
Authorization: Bearer TU_TOKEN

{
    "cargo": "Senior Analista"
}

PATCH http://127.0.0.1:8002/api/empleados/1/estado
Content-Type: application/json
Authorization: Bearer TU_TOKEN

{
    "estado": "inactivo"
}