POST http://127.0.0.1:8001/api/auth/login
Content-Type: application/json

{
    "usuario": "admin",
    "contrasena": "admin123"
}

GET http://127.0.0.1:8001/api/auth/validar
Authorization: Bearer TU_TOKEN

POST http://127.0.0.1:8001/api/auth/logout
Authorization: Bearer TU_TOKEN